- requirements.txt
- test/fake_gpiozero.py
- test/pi_patch.py
- test/test_raspberryPi_monitorPi.py
Following the discussions in #5 I propose you the following solution inspired by this repo : https://pypi.org/project/fake-rpi/
We create fakes Raspberry pi library classes for the tests, and we use the pi_patch module to replace the real ones by the fake ones during the tests. I find this solution quite elegant and it solves our problem. It's not perfect because we don't reproduce the exact working conditions but it's similar
What do you think ?
> Test patch

- server/docker-compose.yml
- server/src/Dockerfile
This small PR aims at allowing webser to access pyroengine 
Plus, the restart option has been added in order to handle webserver reboot.
I have some issues with pyroengine dependencies (will be fixed in another PR) so `server/src/requirements.txt` has not be updated. 
Feedback are welcome !
> Allow webserver pyroengine use

- server/src/Dockerfile
- server/src/requirements.txt
This PR aims at successfully building the webserver with pyro-vision dependencies. 
Some builds of pyro-vision requirements seems to not be available for alpine docker image ([open-cv]( https://stackoverflow.com/questions/50950588/trouble-installing-opencv-in-docker-container-using-pip), torch), and I cannot succeed to build the image with `pyro-vision` in requirements. 
Hence, this PR provides a **Dockerfile based on slim image** that allow webserver to be built with pyro-vision package
Btw : Some [resources](https://pythonspeed.com/articles/base-image-python-docker-images/) states that python could be faster on slim image than on alpine, that is a good point too. 
As long I am not so much knowledgeable, maybe some commands in the dockerfile could be removed to lighten the image. …
> Solve vision dependencies compliance - alpine to slim docker image 

- server/docker-compose.yml
Hi everyone ! 
Small PR to fix an issue that occurs once the main rpi is under the VPN (provided by OpenVPN) and we have to launch the Docker build: it does not. The error is the following `ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network`.
According to [this](https://stackoverflow.com/questions/43720339/docker-error-could-not-find-an-available-non-overlapping-ipv4-address-pool-am) and since the main rpi is under OpenVPN, and especially the answer of people having such trouble with OpenVPN, the idea of the fix is to « specify what exactly subnet you want to use.» and this implies to add a « network » section in the `docker-compose.yml`:
```
networks:
default:
driver: bridge
ipam:
config:
- subnet: 172.16.57.0/24
```
This …
> Add network in docker-compose to allow for use under OpenVPN

- pyroengine/pi_utils/runner.py
- test/fake_picamera.py
- test/pi_patch.py
- test/test_runner.py
Hi everyone ! 
I have taken the liberty of rewriting `runner.py` so that it matches the structure of `monitor_pi.py`, namely:
- create a class
- add logger (because I think that in the future it might be nice to catch the errors if some happens corresponding to RequestException, but for that I shall create rotating logs first, but anyways, not a priority)
- add corresponding unit tests
I proposed this new structure, any feedback is welcomed ! 🤗 
However I have a question regarding the code that was already in `runner.py`. \
The instantiation `stream = io.BytesIO()` was done two times: one before the loop (line 22) and one in the loop (line 27). Why is that ? \
The one in the loop overtakes the previous one. I'm not familiar with `io.Bytes`: do we need to re-instantiate it everytime we …
> Rewrite of runner.py to make it similar to monitor_pi.py

- pyroengine/pi_utils/check_internet_connection.sh
Hi everyone, 
In this PR you can find a proposition for internet failures scenario. This script bash will then be added on the main rpi (using pyro-sys-setup) and will be put in a cron job so that in it run every 15 minutes for instance (the number here is chosen arbitrarily, if you have better ideas, feel free to tell me).
The flow is the following:
```
Ping internet: 
- if success: 
Ping vpn:
- if success: ok exit 
- if failure: restart vpn
- if failure: restart of network interfaces (all interfaces because I don't know which internet the 4G modem will take)
sleep 60 sec
Ping internet again (to make sure that we have internet):
- if success: ok exit
- if failure: reboot
```
What do you think ?
> Add bash script for internet failures scenario

- pyroengine/pi_utils/runner.py
- server/src/app/api/routes/inference.py
- server/src/app/api/routes/write_image.py
- server/src/app/main.py
- server/src/tests/routes/test_write_image.py
This PR aims at adding a way to take a single picture in a pi camera, send it to a main RPI and write it locally. This will simplify the hardware installation process and possibly future checks.
This is just a draft code / minimal example to initiate the discussion, no checks and tests added. If this is included, the next step could be to have an interface to request pictures from specific pi camera devices and view the latest ones in the local pi main web server.
> Take picture in pi camera, send and write in pi main

- pyroengine/engine/engine.py
- pyroengine/pi_utils/reboot_router.py
- reordered imports
- changed console print to `logging.info` for a cleaner history of events on the device
- fixed a comment that was added as a bare string
> refactor: Switched console print to logging.info

- pyroengine/engine/engine.py
This PR simply adds a `heartbeat` (ping) at each frame prediction when the frame sender is known.
> feat: Added heartbeat at each frame prediction

- main.rpi.requirements.txt
- requirements.txt
- removes unused `pandas` dependency since it's quite heavy for low-power devices
- unpinned `pyroclient` from dependencies of the main Raspberry (@chloeskt could you review this carefully please? I'm not sure why it was pinned in the first place, so I might have missed something)
> chore: Updated requirements.txt

- pyroengine/engine/engine.py
- pyroengine/engine/predictor.py
- requirements.txt
- test/test_engine.py
- unified alert uploading: any detected alert is put in a cache (with a max size), and the object tries to empty this cache by uploading the alerts in it at every prediction it does. This means that if the connection is lost during N detections and comes back after this, it will dutifully upload the media and send the alerts for those in cache (limited to the cache size obviously)
- added an automatic cache backup system: this cache is backup to disk every hour by default. Everytime the engine is instantiated it tries to restore the cache from disk. Which means that when we reboot the device to get back the connection, it will load back everything that was saved to disk.
- updates requirements
- updates unittests
One point to pay attention …
> feat: Added an alert cache mechanism to avoid loosing information without internet

- pyroengine/pi_utils/check_internet_connection.sh
This script to solve connection problems does not restart the rooter. We saw that the majority of the connection problems come from the rooter it is therefore essential to restart it in case of connection loss
> Improved router reboot script

- requirements.txt
Let's install pyro-vision from repo to keep it uptodate !
> chore: Installed pyrovision from source

- pyroengine/pi_utils/pi_zeros/monitor_runner.sh
The aim of this PR is to replace the PR #69, this solution allows thanks to a bash script to keep the runner alive.
This script must be added to the crontab to be launched at reboot time
@reboot bash /home/pi/pi_zeros/monitor_runner.sh
> add monitor runner

- pyroengine/pi_utils/pi_zeros/runner.py
The default  time between two frames should be 30s and not 3
> change default loop interval

- .github/validate_headers.py
- docs/source/conf.py
- pyroengine/pi_utils/ip_hostname_mapping.py
- pyroengine/pi_utils/pi_zeros/monitor_pi.py
- pyroengine/pi_utils/pi_zeros/runner.py
- scripts/collect_env.py
- server/src/app/api/routes/inference.py
- server/src/app/api/routes/metrics.py
- server/src/app/api/routes/write_image.py
- server/src/app/api/schemas.py
- server/src/app/config.py
- server/src/app/main.py
- server/src/tests/routes/test_metrics.py
- setup.py
- test/fake_gpiozero.py
- test/fake_picamera.py
- test/pi_patch.py
- test/test_engine.py
- test/test_raspberryPi_monitorPi.py
- test/test_utils.py
> black formatting

- requirements.txt
Matplotlib deps not needed for onnx inference
> remove matplotlib

- runner/src/runner.py
Naming issue, tested on test tour
> fix variable name (#90)

- runner/src/runner.py
It can be useful to save the images on the pi for debug purposes. This PR adds this option, you just have to add a variable save_img_debug to config_data.json:
```
{
"detection_threshold": 0.25,
"api_url": "https://api.pyronear.org",
"save_evry_n_frame": 50,
"loop_time": 7.5,
"latitude": 48.8673439026,
"longitude": 2.3841824532,
"model_weights": "data/yolov5s_v001.onnx",
"save_img_debug": True,
}
```
> save img for debug

- pyroengine/engine/engine.py
Small PR to have two different messages in case of detection or not
> improve logs

- .gitignore
Config data folder must be ignored
> ignore config data

- .github/workflows/release.yml
- README.md
This PR adds a CI job to build and push docker images for both linux/amd64 and linux/arm64, following this tutorial: https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54
Closes #103 
> ci: Added multi-arch docker build upon release

- .github/workflows/tests.yml
- pyproject.toml
- pyroengine/core.py
- tests/conftest.py
- tests/test_engine_core.py
- tests/test_engine_vision.py
- updates test dependencies
- passes down .env from the CI
- adds unittests with the API
- improves logging in Engine
- renames `client_creds` into `cam_creds`
- fixes edge case for state update
- return HTTP response in private methods (for unittests)
Closes #51
> test: Added unittests with Alert API

- .github/workflows/doc-status.yml
- .github/workflows/docs.yml
- README.md
This PR fixes the documentation badge of the README.
> docs: Fixed readme badge for documentation

- docker-compose.yml
The size of the logs is not yet a problem, but on the one hand we have quite a lot of logs (especially in case of trouble), and on the other hand the current approach is to simply make the log file grow infinitely ♾️  !
Hence, in order to prevent possible future issues, we should manage log files rotation and remove oldest. 
Fortunately, this can be done in a few lines with [docker](https://docs.docker.com/config/containers/logging/json-file/). 
This PR introduces the following modifications : 
- Adds logging to docker compose (json-file logging driver, size max and 5 file max)
As long as there space available on devices, I've picked max-size as 100mo and 5 file maximum but open to discuss it :) 
Happy to discuss it 😄 
PS : log files are accessible at …
> feat: Added log management

- pyroengine/engine.py
When internet is down, heartbeat raise an error witch is catch by this [try/catch](https://github.com/pyronear/pyro-engine/blob/b1533c55f05faa56717e56a26a4b7571bfc17703/pyroengine/core.py#L37) and lead to "Unable to analyze stream from camera xx" warning. If think it's better to add a heartbeat try/catch for clarity purpose
> catch heartbeat error

- pyroengine/engine.py
- src/run.py
The purpose of this pr is to make all engine parameters accessible from run so it is easier to test different configurations.
Also I changed some default values.
frame_size 4k > 720,1280 the 4k image is too heavy for some towers
jpeg_quality 50 > 80, the compression was too strong with some artifacts especially in low light
cache-size 100 > 20 to try not to saturate the ram
alert_relaxation 3 > 2 because the model is better now I propose to decrease the alert_relaxation
> Make all params availables from run

- pyroengine/core.py
- src/run.py
We had a problem for several months now, the system is blocking and not analyzing any image while the docker is not stopped. We investigated with @fe51 these last days and we finally found the problem. It seems that some calls to the api don't have a timeout which makes the system wait forever.
While waiting for this problem to be fixed on the api side, I propose the following fix. I added a timeout on the call of the analyze stream function for each camera. The execution time of this function should not exceed period / number of cameras (in our case 30 /4 = 7.5 s).
Even if this code is a hotfix, it might make sense to keep it in the future. Even if the bug has been fixed on the api side
> analyze stream timeout

- Dockerfile
Our current docker image [python:3.8.1-slim](https://hub.docker.com/layers/library/python/3.8.1-slim/images/sha256-f4fa27e3c1004088eac76590b800f1efa813cc9baae827dee152895deba2fd28?context=explore) haven't been updated for 3 year now, let's use [python:3.8.16-slim](https://hub.docker.com/layers/library/python/3.8.16-slim/images/sha256-92689d355058ec11621b8ad082b5e9191143aac0019051aaff702ede49ed2502?context=explore) instead
> update docker img

- pyroengine/engine.py
- pyroengine/vision.py
- src/run.py
- tests/test_engine.py
Hello,
The counter we're currently using poses a problem if we have the following prediction sequence (0: no_fire, 1:fire):
1 0 1 1 0 1 1 1 1
We'll start transmitting images from frame 7 onwards, although the previous images are probably interesting.
What's more, we're not using our model's location information, so two FPs in different places will increase the counter together.
I therefore propose a new strategy, combining the results of N consecutive frames. As shown in the schema below, the idea is to perform an NMS on all the boxes amoung the N frames, then for each resulting box, sum up the score of each box with an intersection >0. In the schema, we sum up all the red boxes to obtain a score of 1.21.
The new detection threshold is conf_th * N, i.e. here 0.25 x 4 = 1. Only the red box …
> New alerte strategy

- pyroengine/engine.py
- pyroengine/vision.py
- tests/test_vision.py
Hi there,
The idea of this PR comes from @fe51, the idea is to use a mask of occlusion in order not to consider the predictions on a zone of the image. This will enable us to avoid FPs in the middle of the sky. This will enable us to hide specific problem areas in a quarry, for example.
> Occlusion mask

- pyproject.toml
Now that bbox management is merged into main on the api side, we can use the main branch as a reference.
> install from main

- pyroengine/engine.py
Due to a recent api problem, we propose to limit the size of bboxes sent. We send a maximum of 5 boxes with 3 decimals.
> limit bbox size

- pyroengine/engine.py
While we wait for the [bbox branch](https://github.com/pyronear/pyro-api/pull/267) merge, we have to stop sending bboxes.
> don't send bbox

- pyroengine/engine.py
if combine_predictions or preds is empty the [0] raise an error, because the np.sum(ious) will work anyway let's remove it
> prevent empty

- pyroengine/engine.py
We can send bboxes again with [pr #267](https://github.com/pyronear/pyro-api/pull/267) merge so let's do it :) 
Small change too, there was an unnecessary string conversion
> Send bbox again

- pyroengine/engine.py
From the PR we take into account all boxes with a score > 0.05 to combine them, which allows us to take into account predictions with a score slightly lower than the threshold. However, we don't want to send these boxes to the api, as there's no reason to display them on the platform.
> filter boxes with low score

- pyroengine/utils.py
- pyroengine/vision.py
- tests/test_vision.py
We use a letterbox transformation for the yolo, which adds padding to the image. This padding was not taken into account in the bounding box, resulting in an offset in the bbox displayed on the platform
> fix padding

- scripts/update_script.sh
Before updating the bastion, we add this scriipt which automatically launches an action on the pi via github in case of a problem
> new script

- pyroengine/engine.py
Two small problems have been identified with this combination of boxes:
We have 4 boxes in memory plus the current box, so we need to divide by self.nb_consecutive_frames + 1.
On the other hand, each time you have to return the prediction and not the result of the nms for display on the platform.
> fix bbox combine

- Dockerfile
from time to time the docker build crashes on some devices due to a pip timeout caused by a bad connection, so I propose to increase the limit
> increase timeout

- .github/workflows/build-push-image.yml
- Makefile
I have created a test env which will be launched every night so it would be good to update our image in dockerhub regularly
> Add new gitAction to push docker images to dockerhub

- .github/workflows/build-push-image.yml
- pyroengine/engine.py
According to this remark : https://github.com/pyronear/pyro-api/pull/320#discussion_r1579565110
> GitAction should not be launched if a PR is closed but not merged

- pyroengine/utils.py
- pyroengine/vision.py
- tests/test_vision.py
Hi, I hadn't done a test with images of different sizes and I realized that the resize was not adapted. We don't need a letterbox (as is the case when training) but simply the following resizing.
I modified the model in onnx format on hugging face by exporting with the “dynamic” parameter to adapt to any image size. The dimensions simply have to be a multiple of 32
> Fix onnx prediction

- Makefile
- docker-compose.yml
- scripts/setup-docker-compose.sh
Hi @RonanMorgan  , sorry I think I reviewed a bit too fast last time the pr does not work for me. I suggest you this evolution which is simpler and works without problem. Let me know if it's ok for you
> fix memory limit

- pyroengine/utils.py
- pyroengine/vision.py
- tests/test_vision.py
After reading some disscutions on the ultralytics repo, I had removed the Letterbox preprocessing to gain in simplicity since it was considered unnecessary. I tested it on an image and obtained a similar result. After noticing some strange results this week, I measured the model's performance on an entire dataset using engine and got a much lower result. Using the Letterbox transformation, we get the same results as those obtained with the ultralytics library. Therefore, we need to add it again
Sorry for this error
> Put back Letterbox transform

- pyroengine/core.py
- src/run.py
Small PR for debugging, the aim is to be able to deactvate alert sending so as not to spam the api unnecessarily.
> no alert send

- pyroengine/core.py
prevent fail when frame capture fail
> prevent frame none

- pyroengine/engine.py
From time to time, the api call is quite long (several seconds), which means we lose time in the execution loop, even though this is not mandatory.
> timeout heartbeat

- pyroengine/sensors.py
- src/control_reolink_cam.py
update script with all available commands
> Reolink commands

- .dockerignore
- Dockerfile-cpu
- Makefile
- pyroengine/engine.py
- src/requirements-light.txt
This is a a refactor allowing to reduce the container size of the Engine (from 6G -> 2G) which is very useful for dev purpose 
For that I have used only cpu libraries. This has been done in a new Docker image file in order to keep the possibility to use the gpy libraries
> Create an small size image 

- pyroengine/engine.py
- pyroengine/vision.py
- src/run.py
- tests/conftest.py
After an analysis of the fires of the past year, none exceeded 20% of the image in width, so I suggest filtering out the detections that represent more than 40% of the image (to keep a margin), which are only produced by large clouds that the current model is still mistaken about
> add max bbox size

- pyproject.toml
- pyroengine/vision.py
- tests/test_engine.py
- Fix the use of model_path as input to instantiate the Engine
- Add checks on the model_path and onnx load
> Fix use of input model_path in the engine

- README.md
The format of the credentials.json file has changed a bit with the new data model
> Write new credentials.json format in the README

- scripts/check_internet_connection.sh
The previous version of the script was failing to retrieve the VPN IP using ifconfig, which returned an empty result. This caused the ping to fail and led the system to reboot unnecessarily, even when the internet connection was fine. This update switches to a more reliable method for retrieving the VPN IP and improves stability
> Fix: Prevent constant reboots due to failed internet check

- pyroengine/engine.py
- src/run.py
The engine takes into account several consecutive frames to average the predicitons made by the model. After having tested several values of this parameters with the EvaluationPipeline (https://github.com/earthtoolsmaker/pyro-eval), we notice that setting this parameter to 8 allows to avoid several false positives (-30%) while conserving most detections (-1.5%). Tests have been performed on 70 sequences of fire and 70 sequences of false positive.
Test details are available here:
https://docs.google.com/spreadsheets/d/1v_u4cCko0vaGM2iV7nkdmvA5s_YBXFhalXDmcuKZ_6A/edit?gid=2071703334#gid=2071703334
or
[Pyro Metrics.xlsx](https://github.com/user-attachments/files/20688464/Pyro.Metrics.xlsx)
> Update nb of consecutive frames to 8

- pyroengine/engine.py
This PR improves the robustness of alert generation by ensuring that each frame added to the last_predictions buffer includes bounding boxes, even when the current prediction is empty.
Fallback bboxes are now filled directly in _update_states() from the latest valid detection for the same camera.
This change removes the need to wait for post-processing to fix empty bboxes during _process_alerts().
fill_empty_bboxes() is still kept in case older alerts in the queue need patching (e.g., if engine is restarted).
Ensures alerts are never uploaded with empty bboxes, which could cause API rejections
This change guarantees per-camera consistency and prevents bbox leakage across different camera streams
> Improve bbox fallback handling in engine

- pyroengine/engine.py
When executing predictions the following error was encountered:
engine/pyroengine/engine.py", line 199, in updatestates
matched_preds = preds[iou_match, :]
IndexError: arrays used as indices must be of integer (or boolean) type
The former declaration of iou_match did not specify any type, which, for an empty prediciton, would create an empty array of dtype object, which cannot be used to index another array.
This is fixed by specifying dtype=bool:
`iou_match = np.array([np.max(iou) > 0 for iou in ious], dtype=bool)`
> Bugfix - Specify dtype on iou_match for empty preds

- docker-compose.yml
- pyroengine/core.py
- pyroengine/engine.py
- reolink_api/client/reolink_api_client/client.py
- reolink_api/src/camera/capture.py
- src/run.py
The purpose of this PR is to handle the startup process. We wait for the API to start properly before launching the engine to avoid arbitrary sleeps and error messages.
We also prevent read errors with _safe_get_latest_image
> Fix start up
