pyronear/pyro-engine

test/pi_patch.py
=> fix flake8

Dockerfile, server/src/Dockerfile
This PR aims to stop build our dockers froms scratch but by pulling them from our docker hub. Images are on my docker hub for know, I will move to pyronear docker hub soon ;)
=> update dockers files

server/src/Dockerfile
I just finished building the docker images for armv7, I propose a small PR to add the new image to the docker and close #32 and #14
=> chore: Updated Dockerfile's base image

.github/workflows/main.yml, pyroengine/pi_utils/reboot_router.py, server/src/requirements.txt
The maximum connection time to the 4g rooter is 1 week, so you have to reboot the router at least once a week to maintain this connection. 
We will have to add a call to this function in our cron jobs.
=> Add update rooter module

pyroengine/pi_utils/check_connection_pizero.sh
This very simple script has for goal to ping the main pi from the pizeros to check the connection then to reboot the pizero if this connection is lost. I will create a cron that run this script every 10mn
=> add check connection script

pyroengine/pi_utils/reboot_router.py
This modification has been done on the devices but not on the repo, we need a script to reboot the rooter with a cronjob
=> Switch to script

Dockerfile
This PR fixes the installation of pip setuptools and wheel, while cleaning the APT cache at the end.
=> fix: Fixed dockerfile

runner/src/runner.py
wrong variable name in runner, do not match with engine
=> fix variable name

scripts/update_script.sh
The update script had not been updated for the new runner
=> fix update script

pyroengine/engine/engine.py
We really need a full ci pipeline ...
=> define prob if no pred

.github/FUNDING.yml
This PR simply switches the funding from OpenCollective to GH sponsors.
=> docs: Updated funding

.github/release.yml
This PR adds a template for automatic release note generation based on the tags of each merged PR.
=> ci: Added release note template

README.md
This PR fixes the reference to the documentation theme in the README.
=> docs: Fixed documentation section of the README

.conda/meta.yaml, .github/workflows/release.yml
This PR adds a CI job to build and publish to conda on each release.
=> ci: Added conda build & publish job for releases

docs/source/changelog.rst
This PR adds a missing entry in the changelog of the documentation.
=> docs: Updated changelog

docs/source/conf.py
This PR fixes the target branch of the documentation edit button.
=> docs: Fixed branch target of doc edit button

.conda/meta.yaml, .github/workflows/release.yml, .gitignore, README.md, docs/source/changelog.rst, setup.py
- updates version index
- updates the documentation changelog
- fixed conda recipe and build command
- added Anaconda badge to README
=> chore: Applied post-release modifications

src/capture.py
In capture.py, paths and name of configuration files are from the old architecture of the repo (before the last release)
This short PR introduces the following modifications: 
- in capture.py : updates path to .env 
- in capture.py: updates name and path to camera credentials
Happy to discuss it !
=> fix: Updated config files location in capture.py

pyroengine/core.py, pyroengine/vision.py, tests/test_engine_core.py, tests/test_engine_vision.py
- fixes the resizing for non-squared images
- updates unittests expected shapes
- updates unittests model to save bandwidth
=> fix: Fixes PIL resizing for non squared shapes

pyroengine/vision.py, src/run.py, tests/test_vision.py
This PR adds the option to use a specific commit of HF hub repo for file download. It also adds a case in the unittest.
Closes #123 
=> feat: Adds an option to specify the hash of the HF hub commit

src/capture.py
Copy/paste issue from run module here :)
=> docs: Fixed comment typo

pyroengine/engine.py, src/run.py
We lost a lot of image because of our internet connection. This PR allows us to save all our images locally for 30 days in order to have time to collect them in case of problems.
=> local backup

Makefile
Add log command to makefile. I'm using this command quite often it will be easier to call it like this
=> log with makefile

scripts/update_script.sh
The update script was to working, the if statement was in the wrong way and path were not up to date. I also changed the way to re-launch the docker to use make instead
I will re-create a develop branch to avoid direct update on device
=> fix and improove update scrip

.github/workflows/builds.yml, .github/workflows/docker.yml, .github/workflows/markdown-links.yml, .github/workflows/style.yml, .github/workflows/tests.yml
Ci need to run on upcoming develop branch
=> ci on develop

scripts/update_script_develop.sh
Creation of an update script for the test tower that updates every hour from the develop branch
=> update develop tour

.github/workflows/pi.yml, scripts/update_script_develop.sh, src/run.py
We need to update main branch to include #136
=> Update main branch with fix

pyroengine/engine.py, src/run.py
Previously the local backup was clean after 30 days which could saturate the disk in case of a large number of false positives. So I propose to clean it according to its size
=> clean backup by size

Dockerfile, README.md, docker-compose.yml, docs/source/conf.py, promtail/config.yml, pyroengine/core.py, pyroengine/engine.py, pyroengine/sensors.py, pyroengine/utils.py, pyroengine/vision.py, setup.py, src/capture.py, src/run.py, tests/test_core.py, tests/test_engine.py, tests/test_sensors.py, tests/test_vision.py
Develop is stable, let's merge it into main branch.
In addition of few bugfix, two main update here:
- new device monitoring with Promtail by @fe51 in https://github.com/pyronear/pyro-engine/pull/152
- fix code crash with analyze stream timeout by @MateoLostanlen in https://github.com/pyronear/pyro-engine/pull/153
=>  Update of the main branch

src/run.py
As explain in #164 the goal is to combine 4 frames, I forget to update the default value
=> use 4 frames

scripts/update_script_develop.sh
the updated script doen in #178 need to be done on develop script for testing
=> update dev script

.github/workflows/tests.yml
following a change on the codecov side, we had to switch to token authentication
=> Fixing codecov upload

Makefile, docker-compose.yml
1. using version is obsolete
2. Update the name for somthing clear
3. Drop promptail for now as is it nos use
=> Clean docker compose

pyroengine/utils.py
fixing : https://github.com/pyronear/pyro-engine/actions/runs/9174885596/job/25226689212?pr=198
=> fix mypy tqdm

pyproject.toml
same as https://github.com/pyronear/pyro-platform/pull/155
=> set pyro-api commit number 

pyroengine/core.py, tests/test_core.py
The current code determines whether it's day or night based on a camera switching to ir mode, but they don't all switch at the same time, generating false positives when switching from day to night
=> mesure for each cam

pyroengine/core.py, tests/test_core.py
This new method makes it possible to sleep for 1 hour between two checks at night, so as not to use the cameras too much.
We're also fixing the static cam test that wasn't done before.
=> Imprrove day check

.github/workflows/build-push-image.yml, .github/workflows/builds.yml, .github/workflows/doc-status.yml, .github/workflows/docker.yml, .github/workflows/docs.yml, .github/workflows/gh-page.yml, .github/workflows/pi.yml, .github/workflows/release.yml, .github/workflows/style.yml, .github/workflows/tests.yml
V2 is deprecated let's use v4 for unitest, let's update all versions to V4
=> update test version

src/run.py
We need to use env var for environment management
=> Fix api url hard coded

src/control_reolink_cam.py, tests/test_sensors.py
=> remove dlt ptz

README.md, docker-compose.yml, src/run.py
=> remove lat, lon

scripts/check_internet_connection.sh
Our new RUT200 routers support SSH reboot, so we’re adding this feature to the internet management script.
It’s especially useful on sites where the connection is unstable
=> reboot rooter

pyroengine/core.py
Let's check if the camera is streaming before each movement to avoid undesired behavior
=> test availability

pyroengine/vision.py
=> Artistic alpaca

Makefile, docker-compose.yml
We were not rebuilding live_stream with run
=> build live_stream image

pyroengine/vision.py
https://github.com/earthtoolsmaker/pyronear-mlops/releases/tag/v1.1.0
=> New model  artistic-alpaca_v1.1.0_fe129f2

src/capture_all_positions.py, src/control_reolink_cam.py, src/setup_positions.py
The purpose of this pr is to improve camera control scripts for setup, in particular
- change the default address in control
- loop on both cameras in setuppositions and capture all
=> Update control cameras scripts

.github/workflows/builds.yml, Dockerfile, pyproject.toml
switch back to use setuptools better for raspberry pi install
=> use setuptools

scripts/check_internet_connection.sh
This PR includes the following changes:
1. Updated `.env` path to `/home/engine/.env`
2. Replaced unsafe env loading with `source`-based logic
3. Normalized `ENABLE_ROUTER_REBOOT` to lowercase for reliability
4. Enabled use of `.env` password with `sshpass` for router reboot
=> Update `check_internet_connection.sh` script

pyroengine/engine.py
In the Engine we instantiate the Classifier as follows:
`self.model = Classifier(model_path=model_path, conf=0.05, max_bbox_size=max_bbox_size)`
The default value for conf is `0.15`in the Classifier definition.
The value of 0.05 is hardcoded in the call and cannot be parametrized from outside. 
This PR allows to instantiate an Engine by specifying this value.
=> [WIP] Add a parameter to the Engine to control model confidence threshold
